// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpnCRhAfoZXWNY2GXqu7D0HwgeHeTaS5g',
    appId: '1:922475661723:web:29eaa91909283f8520f93e',
    messagingSenderId: '922475661723',
    projectId: 'employee-management-app-15dd7',
    authDomain: 'employee-management-app-15dd7.firebaseapp.com',
    storageBucket: 'employee-management-app-15dd7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnv_XCAdERGqGZl-j8N8bOEasbiFtaR2k',
    appId: '1:922475661723:android:909e2731d13eaad020f93e',
    messagingSenderId: '922475661723',
    projectId: 'employee-management-app-15dd7',
    storageBucket: 'employee-management-app-15dd7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBybtHFS13D3Gu1XC_rziaG9s7_k8xkKkE',
    appId: '1:922475661723:ios:7e6ee87d08c3fe3f20f93e',
    messagingSenderId: '922475661723',
    projectId: 'employee-management-app-15dd7',
    storageBucket: 'employee-management-app-15dd7.firebasestorage.app',
    iosBundleId: 'com.example.helloFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBybtHFS13D3Gu1XC_rziaG9s7_k8xkKkE',
    appId: '1:922475661723:ios:7e6ee87d08c3fe3f20f93e',
    messagingSenderId: '922475661723',
    projectId: 'employee-management-app-15dd7',
    storageBucket: 'employee-management-app-15dd7.firebasestorage.app',
    iosBundleId: 'com.example.helloFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpnCRhAfoZXWNY2GXqu7D0HwgeHeTaS5g',
    appId: '1:922475661723:web:e192e85fc55f0b2320f93e',
    messagingSenderId: '922475661723',
    projectId: 'employee-management-app-15dd7',
    authDomain: 'employee-management-app-15dd7.firebaseapp.com',
    storageBucket: 'employee-management-app-15dd7.firebasestorage.app',
  );
}
